### ISSUE TITLE
garage leave not working (error in console)

### ISSUE THREAD

**Issue by xTreame** [CommunityUnionRP/Union#2]
garage leave is not working. there appears a error in console. I will attach the error asap.

**Comment by xTreame** [comment]
../ragemp-srv/packages/union-rp/events/HouseEvents.js:126: TypeError: Cannot read property 'showFor' of undefined
        interior.garageMarker.showFor(player);

**Comment by xTreame** [comment]
solved. some houses have no garages defined in database (no coordinates)

**Comment by CommunityUnionRP** [comment]
Ok! If you can, you need to make a merge request with the corrected error.
